/* BKL V0.9.9.1: globale News, Orga und Master */
(()=>{'use strict';
const $=id=>document.getElementById(id),sb=()=>window.bklSupabase;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[],canEdit=false;
const dt=x=>new Date(x).toLocaleDateString('de-DE',{day:'2-digit',month:'long',year:'numeric'});
async function load(){if(!sb())throw Error('Supabase nicht verbunden');const {data,error}=await sb().from('bkl_news').select('*').order('published_at',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false});if(error)throw error;items=data||[];}
function newsCard(n){return `<article class="n991-card">${n.image_url?`<img class="n991-img" src="${esc(n.image_url)}" alt="Bild zur Nachricht" loading="lazy">`:''}<small>${esc(dt(n.published_at||n.created_at))}</small><h2>${esc(n.title)}</h2><p class="n991-body">${esc(n.body)}</p>${n.link_url?`<a href="${esc(n.link_url)}" target="_blank" rel="noopener noreferrer">Mehr erfahren ↗</a>`:''}</article>`;}
function renderHome(){const card=$('homeNewsCard');if(!card)return;const n=items.find(x=>x.is_published);const title=$('homeNewsEventName');if(title)title.textContent=n?n.title:'BKL';const p=card.querySelector('p');if(p)p.textContent=n?(n.body.length>220?n.body.slice(0,217)+'…':n.body):'Hier erscheinen später aktuelle Meldungen, Anmeldeinfos und wichtige Hinweise rund um den Bierkistenlauf Polch.';}
function renderPublic(){const host=$('bklNews991');if(!host)return;host.innerHTML='<h1>NEWS</h1><p>Aktuelles rund um den Bierkistenlauf Polch</p>'+ (items.filter(x=>x.is_published).map(newsCard).join('')||'<p>Noch keine Nachrichten veröffentlicht.</p>');}
function renderAdmin(){const host=$('bklNews991Admin');if(!host)return;host.innerHTML=`<h1>NEWS-VERWALTUNG</h1><p>Nachrichten erstellen, bearbeiten, als Entwurf speichern und veröffentlichen.</p><button class="btn btn-orange" id="n991new">+ NEUE NEWS</button>`+items.map(n=>`<article class="n991-adminrow"><b>${esc(n.title)}</b><span>${n.is_published?'VERÖFFENTLICHT':'ENTWURF'}</span><button class="mini-action" data-editnews="${n.id}">BEARBEITEN</button></article>`).join('');$('n991new').onclick=()=>edit();host.querySelectorAll('[data-editnews]').forEach(b=>b.onclick=()=>edit(items.find(n=>n.id===b.dataset.editnews)));}
async function refresh(){await load();renderHome();renderPublic();if(canEdit)renderAdmin();}
function edit(n){const d=$('n991dialog');d.innerHTML=`<form class="n991-form"><h2>${n?'NEWS BEARBEITEN':'NEUE NEWS'}</h2><label>Titel<input name="title" required maxlength="160" value="${esc(n?.title||'')}"></label><label>Nachricht<textarea name="body" required rows="7">${esc(n?.body||'')}</textarea></label><label>Bild (optional)<input type="file" name="image" accept="image/png,image/jpeg,image/webp"></label><label>Bild-URL (optional)<input name="image_url" type="url" value="${esc(n?.image_url||'')}"></label><label>Weiterführender Link (optional)<input name="link_url" type="url" value="${esc(n?.link_url||'')}"></label><label class="n991-check"><input type="checkbox" name="published" ${n?.is_published?'checked':''}> Jetzt veröffentlichen</label><div class="n991-buttons"><button type="button" id="n991cancel" class="mini-action">ABBRECHEN</button><button type="submit" class="btn btn-orange">SPEICHERN</button>${n?'<button type="button" id="n991delete" class="mini-action">LÖSCHEN</button>':''}</div><p id="n991error" role="alert"></p></form>`;d.showModal();$('n991cancel').onclick=()=>d.close();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const err=$('n991error');try{const payload={title:String(f.get('title')).trim(),body:String(f.get('body')).trim(),image_url:String(f.get('image_url')||'').trim()||null,link_url:String(f.get('link_url')||'').trim()||null,is_published:f.has('published')};if(!payload.title||!payload.body)throw Error('Titel und Text sind erforderlich.');const file=f.get('image');if(file?.size){if(file.size>5*1024*1024)throw Error('Bild maximal 5 MB');const ext=({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'})[file.type];if(!ext)throw Error('Nur JPG, PNG oder WebP');const path=`news/${crypto.randomUUID()}.${ext}`;const {error:up}=await sb().storage.from('bkl-news-images').upload(path,file,{contentType:file.type});if(up)throw up;payload.image_url=sb().storage.from('bkl-news-images').getPublicUrl(path).data.publicUrl;}if(payload.is_published&&!n?.is_published)payload.published_at=new Date().toISOString();const q=n?sb().from('bkl_news').update(payload).eq('id',n.id):sb().from('bkl_news').insert(payload);const {error}=await q;if(error)throw error;d.close();await refresh();}catch(x){err.textContent=x.message;}};if(n)$('n991delete').onclick=async()=>{if(!confirm('Diese News endgültig löschen?'))return;const {error}=await sb().from('bkl_news').delete().eq('id',n.id);if(error){$('n991error').textContent=error.message;return;}d.close();await refresh();};}
function init(){const page=document.createElement('section');page.id='bklNews991Page';page.className='page';page.innerHTML='<div id="bklNews991" class="n991-wrap">News werden geladen …</div>';document.body.appendChild(page);const admin=document.createElement('section');admin.id='bklNews991Admin';admin.className='n991-wrap admin-workspace hidden';document.querySelector('#adminPage')?.appendChild(admin);const d=document.createElement('dialog');d.id='n991dialog';document.body.appendChild(d);
document.addEventListener('click',e=>{const b=e.target.closest('[data-page="news"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(typeof closeMenu==='function')closeMenu();document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));page.classList.add('active-page');window.scrollTo(0,0);refresh().catch(x=>{$('bklNews991').textContent='News konnten nicht geladen werden: '+x.message;});},true);
document.addEventListener('click',async e=>{if(!e.target.closest('[data-admin-module="news991"]'))return;e.preventDefault();e.stopImmediatePropagation();const {data,error}=await sb().rpc('is_admin');if(error||data!==true){alert('Nur Orga-Team und Master-Admins dürfen News verwalten.');return;}canEdit=true;if(typeof closeAdminPanels==='function')closeAdminPanels();admin.classList.remove('hidden');admin.scrollIntoView({block:'start'});try{await refresh();}catch(e){admin.textContent='News konnten nicht geladen werden: '+e.message;}},true);
// Startseite aktualisieren, auch bei Rueckkehr.
refresh().catch(()=>{});document.addEventListener('click',e=>{if(e.target.closest('[data-page="home"]'))setTimeout(()=>refresh().catch(()=>{}),100);},true);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
