/* BKL V0.9.8.9: Globale Sponsoren – unabhängig von Veranstaltungen. */
(()=>{'use strict';
const $=id=>document.getElementById(id);
const db=()=>window.bklSupabase;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
const master=()=>{try{return demoRole==='master'&&!!currentAuthUser}catch{return false}};
let rows=[];
function status(msg,error=false){const el=$('bklSponsorStatus');if(el){el.textContent=msg;el.style.color=error?'#ff7777':'#b9d7b9'}}
function cards(items){if(!items.length)return '<span>SPONSOR</span><span>SPONSOR</span><span>SPONSOR</span>';return items.map(x=>{const logo=safeUrl(x.logo_url||'');const link=safeUrl(x.website_url||'');const content=`${logo?`<img loading="lazy" src="${esc(logo)}" alt="${esc(x.name)}" />`:`<strong>${esc(x.name)}</strong>`}`;return link?`<a class="bkl-sponsor-tile" href="${esc(link)}" target="_blank" rel="noopener noreferrer" aria-label="Webseite von ${esc(x.name)} öffnen">${content}</a>`:`<div class="bkl-sponsor-tile" aria-label="${esc(x.name)}">${content}</div>`}).join('')}
async function publicLoad(){if(!db())return;const {data,error}=await db().from('bkl_global_sponsors').select('name,logo_url,website_url,sort_order').eq('is_visible',true).order('sort_order').order('name');if(error){console.warn('Sponsoren:',error.message);return}const host=$('bklHomeSponsors');if(host)host.innerHTML=cards(data||[])}
function render(){const host=$('bklSponsorList');if(!host)return;host.innerHTML=rows.length?rows.map(x=>`<article class="bkl-sponsor-item" data-sponsor="${esc(x.id)}"><h3>${esc(x.name)}</h3><label>Name<input data-field="name" maxlength="120" value="${esc(x.name)}"></label><label>Webseite (optional)<input data-field="website_url" type="url" placeholder="https://" value="${esc(x.website_url||'')}"></label><label>Beschreibung (optional)<textarea data-field="description" rows="2">${esc(x.description||'')}</textarea></label><label>Logo-URL (optional)<input data-field="logo_url" type="url" placeholder="https://" value="${esc(x.logo_url||'')}"></label>${safeUrl(x.logo_url||'')?`<img class="bkl-sponsor-preview" src="${esc(safeUrl(x.logo_url))}" alt="Logo">`:''}<label>Logo hochladen (PNG, JPG, WebP, GIF; max. 5 MB)<input data-upload type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label><label><input data-field="is_visible" type="checkbox" ${x.is_visible?'checked':''}> Öffentlich anzeigen</label><label>Reihenfolge<input data-field="sort_order" type="number" value="${Number(x.sort_order)||0}"></label><div class="bkl-sponsor-actions"><button class="mini-action" data-save="${esc(x.id)}">SPEICHERN</button><button class="mini-action" data-delete="${esc(x.id)}">LÖSCHEN</button></div></article>`).join(''):'<p>Noch keine Sponsoren angelegt.</p>';host.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(b.dataset.save));host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete))}
async function refresh(){if(!db())return status('Keine Verbindung zu Supabase.',true);const {data,error}=await db().from('bkl_global_sponsors').select('*').order('sort_order').order('name');if(error)return status('Laden fehlgeschlagen: '+error.message,true);rows=data||[];render();status(rows.length+' Sponsoren geladen.')}
async function save(id){if(!master())return status('Nur Master-Admins.',true);const el=[...document.querySelectorAll('[data-sponsor]')].find(x=>x.dataset.sponsor===id);if(!el)return;const val=k=>el.querySelector(`[data-field="${k}"]`)?.value?.trim()||'';const name=val('name'),web=val('website_url'),logo=val('logo_url');if(!name)return status('Name fehlt.',true);if((web&&!safeUrl(web))||(logo&&!safeUrl(logo)))return status('Bitte gültige http(s)-Links eingeben.',true);const row={name,website_url:web||null,logo_url:logo||null,description:val('description')||null,sort_order:parseInt(val('sort_order'),10)||0,is_visible:el.querySelector('[data-field="is_visible"]').checked,updated_at:new Date().toISOString()};try{const file=el.querySelector('[data-upload]')?.files?.[0];if(file){if(file.size>5242880)throw Error('Logo zu groß (max. 5 MB).');const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif'}[file.type];if(!ext)throw Error('Ungültiger Bildtyp.');const path=`global/${crypto.randomUUID()}.${ext}`;const uploaded=await db().storage.from('bkl-sponsor-logos').upload(path,file,{contentType:file.type});if(uploaded.error)throw uploaded.error;row.logo_url=db().storage.from('bkl-sponsor-logos').getPublicUrl(path).data.publicUrl}const {error}=await db().from('bkl_global_sponsors').update(row).eq('id',id);if(error)throw error;await refresh();await publicLoad();status('Sponsor gespeichert.')}catch(e){status('Speichern fehlgeschlagen: '+e.message,true)}}
async function remove(id){if(!master()||!confirm('Sponsor wirklich löschen?'))return;const {error}=await db().from('bkl_global_sponsors').delete().eq('id',id);if(error)return status('Löschen fehlgeschlagen: '+error.message,true);await refresh();await publicLoad();status('Sponsor gelöscht.')}
async function add(){if(!master())return status('Nur Master-Admins.',true);const name=$('bklNewSponsorName')?.value.trim();if(!name)return status('Name fehlt.',true);const {error}=await db().from('bkl_global_sponsors').insert({name,sort_order:rows.length*10});if(error)return status('Anlegen fehlgeschlagen: '+error.message,true);$('bklNewSponsorName').value='';await refresh();status('Sponsor angelegt. Jetzt Logo und Link ergänzen.')}
window.bklOpenSponsorAdmin=async()=>{const ws=$('adminWorkspace');if(!ws)return;ws.classList.remove('hidden');ws.innerHTML=`<span class="eyebrow">V0.9.8.9 · MASTER</span><h2>SPONSOREN & INHALTE</h2><p>Sponsoren gelten dauerhaft für die gesamte BKL-App und erscheinen auf der Startseite – unabhängig von Veranstaltungen.</p><div class="bkl-sponsor-add"><input id="bklNewSponsorName" placeholder="Sponsorname" maxlength="120"><button id="bklAddSponsor" class="btn btn-orange">+ SPONSOR ANLEGEN</button></div><p id="bklSponsorStatus" role="status"></p><div id="bklSponsorList"></div>`;if(!master()){$('bklAddSponsor').disabled=true;status('Nur Master-Admins dürfen Sponsoren verwalten.',true)}else $('bklAddSponsor').onclick=add;await refresh();ws.scrollIntoView({behavior:'smooth',block:'start'})};
const css=document.createElement('style');css.textContent=`.sponsor-slots .bkl-sponsor-tile{display:flex;min-width:0;min-height:75px;border:1px dashed #383838;border-radius:7px;align-items:center;justify-content:center;padding:8px;box-sizing:border-box;text-decoration:none;color:#fff;overflow-wrap:anywhere}.sponsor-slots .bkl-sponsor-tile img{max-width:100%;max-height:85px;object-fit:contain}.sponsor-slots .bkl-sponsor-tile strong{font-size:12px}.bkl-sponsor-add{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.bkl-sponsor-add input{flex:1;min-width:140px}.bkl-sponsor-item{border:1px solid #66460b;border-radius:12px;padding:14px;margin:14px 0;background:#161616}.bkl-sponsor-item label{display:block;margin:12px 0;color:#ddd}.bkl-sponsor-item input:not([type=checkbox]),.bkl-sponsor-item textarea,.bkl-sponsor-add input{display:block;width:100%;box-sizing:border-box;margin-top:5px;background:#242424;border:1px solid #555;color:white;padding:10px;border-radius:7px}.bkl-sponsor-preview{max-height:90px;max-width:180px;object-fit:contain}.bkl-sponsor-actions{display:flex;gap:12px;flex-wrap:wrap}`;document.head.appendChild(css);
window.addEventListener('load',()=>{setTimeout(publicLoad,700);setTimeout(publicLoad,2800)});document.addEventListener('click',e=>{if(e.target.closest('[data-page="home"]'))setTimeout(publicLoad,250)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)publicLoad()});
})();
